"""empty message

Revision ID: 05e4fc33148a
Revises: add_is_manual_flag_to_commission
Create Date: 2025-11-07 20:56:45.454229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e4fc33148a'
down_revision = 'add_is_manual_flag_to_commission'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission', schema=None) as batch_op:
        batch_op.alter_column('is_manual',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission', schema=None) as batch_op:
        batch_op.alter_column('is_manual',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
