"""area options

Revision ID: 093cc4d3d52a
Revises: b1db398aab9a
Create Date: 2025-11-08 22:02:58.615600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093cc4d3d52a'
down_revision = 'b1db398aab9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('district')

    # ### end Alembic commands ###
