"""empty message

Revision ID: a2eaa7da57f5
Revises: 05e4fc33148a
Create Date: 2025-11-08 19:50:57.597212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2eaa7da57f5'
down_revision = '05e4fc33148a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sale_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sale_end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sale_discount_percentage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('sale_discount_percentage')
        batch_op.drop_column('sale_end_date')
        batch_op.drop_column('sale_start_date')
        batch_op.drop_column('sale_type')

    # ### end Alembic commands ###
