"""add parent_id to category

Revision ID: add_parent_id_to_category
Revises: 9ae64dbb057e
Create Date: 2025-01-31 01:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_parent_id_to_category'
down_revision = '9ae64dbb057e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'category', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'parent_id')
    # ### end Alembic commands ###
