"""sale options

Revision ID: b1db398aab9a
Revises: a2eaa7da57f5
Create Date: 2025-11-08 20:46:36.178774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1db398aab9a'
down_revision = 'a2eaa7da57f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_new_arrival', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('featured_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('new_arrival_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('new_arrival_order')
        batch_op.drop_column('featured_order')
        batch_op.drop_column('is_new_arrival')
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
