"""Add category_id and brand_id to products table

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2025-10-19 16:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f6a7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('brand_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_category_id'), 'category_id')
        batch_op.create_index(batch_op.f('ix_products_brand_id'), 'brand_id')
        batch_op.create_foreign_key('fk_products_category_id', 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key('fk_products_brand_id', 'brands', ['brand_id'], ['id'])
        batch_op.drop_column('category')
        batch_op.drop_column('brand')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_products_brand_id', type_='foreignkey')
        batch_op.drop_constraint('fk_products_category_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_products_brand_id'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))
        batch_op.drop_column('brand_id')
        batch_op.drop_column('category_id')
    # ### end Alembic commands ###
