"""Add store fields to User model

Revision ID: c35ad425a50d
Revises: e97bfc74d7e9
Create Date: 2025-10-19 13:07:03.664756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c35ad425a50d'
down_revision = 'e97bfc74d7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('store_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('store_description')
        batch_op.drop_column('store_name')

    # ### end Alembic commands ###
