"""comment replay feiled add

Revision ID: d1f32140f793
Revises: 2e5efa8afd5a
Create Date: 2026-05-06 12:52:37.032460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f32140f793'
down_revision = '2e5efa8afd5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('replied_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('replied_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('replied_at')
        batch_op.drop_column('reply')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('replied_at')
        batch_op.drop_column('reply')

    # ### end Alembic commands ###
