"""Initial PostgreSQL migration

Revision ID: e97bfc74d7e9
Revises: 26507ca8ccc8
Create Date: 2025-10-19 13:01:57.603918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97bfc74d7e9'
down_revision = '26507ca8ccc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('hex_code', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('colors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_colors_name'), ['name'], unique=True)

    op.create_table('materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_name'), ['name'], unique=True)

    op.create_table('shipping_countries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('estimated_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code')
    )
    with op.batch_alter_table('shipping_countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipping_countries_name'), ['name'], unique=True)

    op.create_table('sizes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sizes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sizes_name'), ['name'], unique=True)

    op.create_table('product_colors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('color_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'color_id', name='_product_color_uc')
    )
    with op.batch_alter_table('product_colors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_colors_color_id'), ['color_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_colors_product_id'), ['product_id'], unique=False)

    op.create_table('product_materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'material_id', name='_product_material_uc')
    )
    with op.batch_alter_table('product_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_materials_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_materials_product_id'), ['product_id'], unique=False)

    op.create_table('product_shipping',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['shipping_countries.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'country_id', name='_product_shipping_uc')
    )
    with op.batch_alter_table('product_shipping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_shipping_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_shipping_product_id'), ['product_id'], unique=False)

    op.create_table('product_sizes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('size_id', sa.String(length=36), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'size_id', name='_product_size_uc')
    )
    with op.batch_alter_table('product_sizes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_sizes_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_sizes_size_id'), ['size_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sizes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_sizes_size_id'))
        batch_op.drop_index(batch_op.f('ix_product_sizes_product_id'))

    op.drop_table('product_sizes')
    with op.batch_alter_table('product_shipping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_shipping_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_shipping_country_id'))

    op.drop_table('product_shipping')
    with op.batch_alter_table('product_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_materials_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_materials_material_id'))

    op.drop_table('product_materials')
    with op.batch_alter_table('product_colors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_colors_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_colors_color_id'))

    op.drop_table('product_colors')
    with op.batch_alter_table('sizes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sizes_name'))

    op.drop_table('sizes')
    with op.batch_alter_table('shipping_countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipping_countries_name'))

    op.drop_table('shipping_countries')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_name'))

    op.drop_table('materials')
    with op.batch_alter_table('colors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_colors_name'))

    op.drop_table('colors')
    # ### end Alembic commands ###
